export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SAVE_SELECTED_CATEGORY = "SAVE_SELECTED_CATEGORY";
export const CHANGED_STATE = "CHANGED_STATE";