export const INITIAL_CONTEXT = null
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY"
export const EDIT_CATEGORY = "EDIT_CATEGORY"
export const VIEW_CATEGORY_DETAILS = "VIEW_CATEGORY_DETAILS"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const CATEGORY_SELECTED = "CATEGORY_SELECTED"